### ISSUE TITLE
Add social media cards

### ISSUE THREAD

**Issue by awesomephant** [awesomephant/desktop-website#5]
We want this sort of thing to happen when someone tweets a link to our website:
![image](https://cloud.githubusercontent.com/assets/2758247/26801962/95a680a2-4a36-11e7-8531-5c098a970faa.png)

This is done through [Twitter Cards](https://dev.twitter.com/cards/overview). You need to add a number of special `<meta>` tags to the `<head>` section which Twitter will interpret. There are different kinds of cards, but I think the [Summary Large Image](https://dev.twitter.com/cards/types/summary-large-image) would be best for us.

The Facebook (and Whatsapp, Slack and a number of other places) equivalent of this is called [Open Graph](http://ogp.me/). It's the same thing, just a different syntax.

## Todo

- [ ] Design image to be used on the card
  - [ ] Research ideal dimensions for this
- [ ] Add `<meta>` Tags
  - [ ] Twitter
  - [ ] Open Graph
- [ ] Test if cards are displayed correctly on all platforms
